changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - "dependabot[bot]"
      - "github-actions[bot]"
  categories:
    - title: Security
      labels:
        - security
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Maintenance
      labels:
        - "*"
